vault_vcenter_hostname: "168.121.48.254"
vault_vcenter_port: "10111"
vault_vcenter_username: "root"
vault_vcenter_password: "cvb123$"

vault_govc_url: "https://168.121.48.254:10111"
vault_govc_username: "root"
vault_govc_password: "cvb123$"
vault_govc_insecure: "1"

vault_ubuntu_password: "ubuntu123"
vault_ubuntu_user: "ubuntu"

vault_ssh_key_passphrase: ""
vault_sudo_password: "ubuntu123"

vault_monitoring_token: "monitoring_token_2024"
vault_backup_encryption_key: "backup_key_2024"

# Usuarios Ubuntu Desktop
vault_ubuntu_desktop_admin_password: "123456"      # Administrador: sudo completo, SSH
vault_ubuntu_desktop_auditor_password: "123456"    # Auditor: solo lectura
vault_ubuntu_desktop_cliente_password: "123456"    # Cliente/Gamer: sin privilegios

# Usuarios Windows 11
vault_windows11_admin_password: "Admin123!"
vault_windows11_auditor_password: "Audit123!"
vault_windows11_cliente_password: "Gamer123!"

# Clave DDNS compartida entre DNS y DHCP
vault_ddns_key_name: "dhcp-key"
vault_ddns_key_algorithm: "hmac-sha256"
vault_ddns_key_secret: "PJvdQJFNFDP/R5tVQaqdLfbuzIwOH2aQLhKPsr5WYyc="
