---
- name: Configurar DHCPv6
  hosts: localhost
  connection: local
  become: true
  
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/all.vault.yml
  
  roles:
    - dhcpv6
  
  tags: dhcp
