---
- name: Configurar DHCPv6
  hosts: localhost
  connection: local
  become: true
  
  vars_files:
    - "{{ playbook_dir }}/../../group_vars/all.yml"
    - "{{ playbook_dir }}/../../group_vars/all.vault.yml"
  
  roles:
    - dhcpv6
  
  tags: dhcp
