---
- name: Configurar DNS/BIND9
  hosts: localhost
  connection: local
  become: true
  
  vars_files:
    - "{{ playbook_dir }}/../../group_vars/all.yml"
    - "{{ playbook_dir }}/../../group_vars/all.vault.yml"
  
  roles:
    - dns_bind
  
  tags: dns