---
# Configuraci贸n de rotaci贸n de logs

- name: "Configurar rotaci贸n de logs del proyecto"
  template:
    src: proyecto-logs.j2
    dest: /etc/logrotate.d/proyecto-ipv6
    mode: '0644'

- name: "Verificar configuraci贸n de logrotate"
  command: logrotate -d /etc/logrotate.d/proyecto-ipv6
  register: logrotate_test
  changed_when: false
  failed_when: false

- name: "Mostrar configuraci贸n de logs"
  debug:
    msg: |
       Rotaci贸n de logs configurada:
      - Logs de BIND9: rotaci贸n semanal, 4 semanas
      - Logs de DHCP: rotaci贸n semanal, 2 semanas  
      - Logs de fail2ban: rotaci贸n diaria, 7 d铆as
      - Compresi贸n autom谩tica habilitada
      
      Ejecutar manualmente: logrotate -f /etc/logrotate.conf