---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload apparmor
  systemd:
    name: apparmor
    state: reloaded

- name: restart isc-dhcp-server6
  systemd:
    name: isc-dhcp-server6
    state: restarted
    enabled: yes
    daemon_reload: yes