---
- name: Instalar ISC DHCPv6 Server
  apt:
    name: isc-dhcp-server
    state: present

# Red ya configurada - solo DHCPv6

- name: Configurar DHCPv6
  template:
    src: dhcpd6.conf.j2
    dest: /etc/dhcp/dhcpd6.conf
  notify: restart isc-dhcp-server

- name: Habilitar IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    state: present
    reload: yes

- name: Asegurar que el servicio isc-dhcp-server esté habilitado y en ejecución
  service:
    name: isc-dhcp-server
    state: started
    enabled: yes
