---
- name: Instalar ISC DHCP Server
  apt:
    name: isc-dhcp-server
    state: present
    update_cache: yes

- name: Crear archivo dhcpd.conf vacío para IPv4
  file:
    path: /etc/dhcp/dhcpd.conf
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Configurar interfaces para DHCP
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
  loop:
    - { regexp: '^INTERFACESv4=', line: 'INTERFACESv4=""' }
    - { regexp: '^INTERFACESv6=', line: 'INTERFACESv6="ens34"' }
  notify: restart isc-dhcp-server

- name: Configurar DHCPv6
  template:
    src: dhcpd6.conf.j2
    dest: /etc/dhcp/dhcpd6.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart isc-dhcp-server

- name: Habilitar IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    state: present
    reload: yes

- name: Asegurar que el servicio isc-dhcp-server esté habilitado y en ejecución
  service:
    name: isc-dhcp-server
    state: started
    enabled: yes
